// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int32
	Name      string
	Email     string
	Age       sql.NullInt32
	CreatedAt time.Time
	UpdatedAt time.Time
	Role      string
}
